# -*- coding: utf-8 -*-
# Opus 4.8-authored podcast specs (content type #3, Podcasts / Watch - audio half).
# gen_podcasts_wave.py expands these into schema-correct passage(kind=podcast)
# + sentence + comprehension item + gloss rows. Host-monologue style; the audio
# transcript == the joined sentence lines (honesty). audio_ref + duration_ms are
# patched later by gen_podcast_audio.py (Gemini TTS -> R2). PROOF wave = 2 (A1,A2).
PODCASTS = [
 dict(level="A1", k="0101", title="My Morning", theme="daily routines",
   about="A short podcast where the host describes a simple morning routine, practising present-simple 'I' verbs and telling the time from A1.",
   lines=[
     ("Hello, and welcome to the Ratel English podcast.", "'Welcome to' is a friendly way to start a show."),
     ("Today, I talk about my morning.", "'Talk about' means to say things on a topic."),
     ("I wake up at seven o'clock.", "'Wake up' means to stop sleeping; we say a clock time with 'at'."),
     ("I drink coffee and eat some bread.", "'And' joins the two things I do."),
     ("Then I go to work by bus.", "'By bus' tells us how the host travels."),
     ("What do you do in the morning?", "This is a question to you, the listener."),
   ],
   checks=[
     dict(q="What time does the host wake up?", why="Line 3 says 'I wake up at seven o'clock.'",
       opts=[("At seven o'clock", True, "Yes - the host wakes up at seven."),
             ("At eight o'clock", False, "No, the host says seven, not eight."),
             ("At six o'clock", False, "No, it is seven o'clock.")]),
     dict(q="How does the host go to work?", why="Line 5 says 'I go to work by bus.'",
       opts=[("By bus", True, "Correct - the host goes by bus."),
             ("By car", False, "The podcast says by bus, not car."),
             ("On foot", False, "No, the host takes the bus.")]),
   ]),
 dict(level="A2", k="0102", title="A Weekend Trip", theme="travel and free time",
   about="The host tells a short story about last weekend, practising past-simple verbs (went, took, saw) from A2.",
   lines=[
     ("Welcome back to the Ratel English podcast.", "'Welcome back' greets listeners who return."),
     ("Last weekend, I went to the mountains.", "'Went' is the past of 'go'."),
     ("I took an early train on Saturday.", "'Took' is the past of 'take'."),
     ("The weather was cold but sunny.", "'Was' is the past of 'is'; 'but' shows a contrast."),
     ("I walked for three hours and saw a lake.", "'Walked' is a regular past verb; 'saw' is the past of 'see'."),
     ("On Sunday, I came home and felt happy.", "'Came' and 'felt' are irregular past verbs."),
     ("Where did you go last weekend?", "We use 'did' to ask a past-simple question."),
   ],
   checks=[
     dict(q="Where did the host go last weekend?", why="Line 2 says 'I went to the mountains.'",
       opts=[("To the mountains", True, "Yes - the host went to the mountains."),
             ("To the beach", False, "No, it was the mountains."),
             ("To a city", False, "The host went to the mountains, not a city.")]),
     dict(q="What was the weather like?", why="Line 4 says 'The weather was cold but sunny.'",
       opts=[("Cold but sunny", True, "Correct - cold but sunny."),
             ("Warm and rainy", False, "No, it was cold but sunny."),
             ("Hot and windy", False, "The podcast says cold but sunny.")]),
   ]),
 dict(level="A1", k="0103", title="My Family", theme="family and home",
   about="The host introduces their family, practising 'have' and simple present-tense descriptions from A1.",
   lines=[
     ("Hello, and welcome back to the Ratel English podcast.", "'Welcome back' greets listeners who return."),
     ("Today, I talk about my family.", "'Talk about' means to say things on a topic."),
     ("I have one sister and one brother.", "We use 'have' to say what belongs to us."),
     ("My sister is a teacher, and my brother is a student.", "'Is' tells us a person's job."),
     ("We live in a small house near the park.", "'Near' means close to something."),
     ("I love my family very much.", "'Very much' makes 'love' stronger."),
     ("How many people are in your family?", "This is a question to you, the listener."),
   ],
   checks=[
     dict(q="How many brothers and sisters does the host have?", why="Line 3 says 'I have one sister and one brother.'",
       opts=[("One sister and one brother", True, "Yes - one of each."),
             ("Two sisters", False, "No, one sister and one brother."),
             ("Three brothers", False, "No, only one brother.")]),
     dict(q="What is the host's sister's job?", why="Line 4 says 'My sister is a teacher.'",
       opts=[("A teacher", True, "Correct - she is a teacher."),
             ("A student", False, "That is the brother's role."),
             ("A doctor", False, "The podcast says teacher.")]),
   ]),
 dict(level="A2", k="0104", title="My Holiday Plans", theme="travel and future plans",
   about="The host shares plans for a summer holiday, practising the 'going to' future and time expressions from A2.",
   lines=[
     ("Welcome back to the Ratel English podcast.", "'Welcome back' greets returning listeners."),
     ("Today, I am going to tell you about my summer plans.", "'Going to' talks about the future."),
     ("Next month, I am going to visit my grandparents.", "'Next month' is a future time expression."),
     ("We are going to stay by the sea for one week.", "'For one week' shows how long."),
     ("I think the weather is going to be warm and sunny.", "'Going to' can also be a prediction."),
     ("I am going to swim every day and read many books.", "'And' joins two future plans."),
     ("What are you going to do this summer?", "A 'going to' question to the listener."),
   ],
   checks=[
     dict(q="Who is the host going to visit?", why="Line 3 says 'I am going to visit my grandparents.'",
       opts=[("Their grandparents", True, "Yes - the grandparents."),
             ("Their friends", False, "No, the grandparents."),
             ("Their teacher", False, "The podcast says grandparents.")]),
     dict(q="How long will they stay by the sea?", why="Line 4 says 'for one week.'",
       opts=[("One week", True, "Correct - one week."),
             ("Two weeks", False, "No, one week."),
             ("One month", False, "'Next month' is when they travel, not how long they stay.")]),
   ]),
 dict(level="B1", k="0105", title="A New Hobby", theme="hobbies and experiences",
   about="The host talks about taking up photography, practising the present perfect for life experiences from B1.",
   lines=[
     ("Hello and welcome to the Ratel English podcast.", "A friendly way to open the show."),
     ("I have recently started a new hobby: photography.", "'Have started' is the present perfect."),
     ("I have always loved taking pictures of nature.", "'Always' with the present perfect covers all my life so far."),
     ("Last year, I bought my first real camera.", "'Bought' is past simple - a finished time, last year."),
     ("Since then, I have taken hundreds of photos.", "'Since then' links a past point to now."),
     ("I have never shared them online, but maybe I will soon.", "'Never' with the present perfect means not at any time up to now."),
     ("Have you ever tried photography?", "'Ever' asks about experience in your whole life."),
   ],
   checks=[
     dict(q="What new hobby has the host started?", why="Line 2 says 'a new hobby: photography.'",
       opts=[("Photography", True, "Yes - photography."),
             ("Painting", False, "No, photography."),
             ("Cooking", False, "The podcast says photography.")]),
     dict(q="When did the host buy their first real camera?", why="Line 4 says 'Last year, I bought my first real camera.'",
       opts=[("Last year", True, "Correct - last year."),
             ("This morning", False, "No, last year."),
             ("Ten years ago", False, "The podcast says last year.")]),
   ]),
 dict(level="B1", k="0106", title="If I Won the Lottery", theme="dreams and imagination",
   about="The host imagines winning the lottery, practising the second conditional (if + past, would + verb) from B1.",
   lines=[
     ("Welcome back to the Ratel English podcast.", "A greeting for returning listeners."),
     ("Today, let's imagine something fun.", "'Let's' invites the listener to do it together."),
     ("If I won the lottery, I would travel around the world.", "Second conditional: an unreal 'if' plus 'would'."),
     ("I would buy a small house by the ocean.", "'Would' describes the imagined result."),
     ("I wouldn't stop working, because I love my job.", "'Wouldn't' is the negative of 'would'."),
     ("If I had more money, I would help my family and friends.", "Another second conditional for an unreal situation."),
     ("What would you do if you won a million?", "A 'would' question to the listener."),
   ],
   checks=[
     dict(q="What would the host do first if they won the lottery?", why="Line 3 says 'I would travel around the world.'",
       opts=[("Travel around the world", True, "Yes - travel the world."),
             ("Stop working", False, "No, they would keep working."),
             ("Buy a car", False, "The podcast says travel.")]),
     dict(q="Would the host stop working?", why="Line 5 says 'I wouldn't stop working, because I love my job.'",
       opts=[("No, because they love their job", True, "Correct - they wouldn't stop."),
             ("Yes, immediately", False, "No, they would keep working."),
             ("Yes, after one year", False, "The podcast says they wouldn't stop.")]),
   ]),
 dict(level="B2", k="0107", title="The Future of Work", theme="technology and the workplace",
   about="The host speculates about how jobs will change, practising future forms and modal speculation from B2.",
   lines=[
     ("Hello, and welcome to the Ratel English podcast.", "A standard opening greeting."),
     ("Have you ever wondered how we will be working in twenty years?", "'Will be working' is the future continuous."),
     ("By 2045, many of us will have changed careers several times.", "'Will have changed' is the future perfect - finished before a future point."),
     ("This time next decade, machines will be handling much of the routine work.", "The future continuous pictures an action in progress later."),
     ("That might sound frightening, but it could also free us to be more creative.", "'Might' and 'could' express possibility."),
     ("Companies that adapt quickly are likely to thrive.", "'Likely to' expresses probability."),
     ("How do you think your own job will evolve?", "A question inviting the listener's prediction."),
   ],
   checks=[
     dict(q="According to the host, what will machines be doing in the future?", why="Line 4 says machines 'will be handling much of the routine work.'",
       opts=[("Handling routine work", True, "Yes - routine work."),
             ("Replacing all humans", False, "No, only the routine work."),
             ("Nothing new", False, "The podcast says they will handle routine work.")]),
     dict(q="How does the host feel about these changes?", why="Line 5 says the changes 'could also free us to be more creative.'",
       opts=[("They could free us to be more creative", True, "Correct - a hopeful view."),
             ("They are completely negative", False, "No, the host sees an upside."),
             ("They will never happen", False, "The host expects them to happen.")]),
   ]),
 dict(level="B2", k="0108", title="A Book That Changed Me", theme="books and personal growth",
   about="The host describes a life-changing book, practising relative clauses and past narration from B2.",
   lines=[
     ("Welcome back to the Ratel English podcast.", "A greeting for returning listeners."),
     ("Today I want to tell you about a book that completely changed the way I think.", "'That changed the way I think' is a relative clause describing the book."),
     ("It was a novel which I discovered by accident in a second-hand shop.", "'Which I discovered' is a relative clause with 'which'."),
     ("The author, whose name I had never heard before, wrote with astonishing honesty.", "'Whose' shows possession inside a relative clause."),
     ("By the time I finished it, I had started to see my own life differently.", "'Had started' is the past perfect - before another past moment."),
     ("It's the kind of story that stays with you for years.", "'That stays with you' is another relative clause."),
     ("Is there a book that has shaped who you are?", "A relative-clause question to the listener."),
   ],
   checks=[
     dict(q="Where did the host find the book?", why="Line 3 says it was found 'by accident in a second-hand shop.'",
       opts=[("In a second-hand shop", True, "Yes - by accident there."),
             ("In a library", False, "No, a second-hand shop."),
             ("Online", False, "The podcast says a second-hand shop.")]),
     dict(q="How had the host changed by the time they finished the book?", why="Line 5 says they 'had started to see my own life differently.'",
       opts=[("They saw their life differently", True, "Correct - a change of perspective."),
             ("They were bored", False, "No, it changed them deeply."),
             ("They forgot it quickly", False, "It stayed with them for years.")]),
   ]),
 dict(level="C1", k="0109", title="The Art of Slowing Down", theme="wellbeing and modern life",
   about="The host reflects on the value of slowing down, practising nominalisation and hedging language from C1.",
   lines=[
     ("Hello, and welcome to the Ratel English podcast.", "A standard opening greeting."),
     ("There is a growing recognition that our obsession with speed comes at a cost.", "'Recognition' and 'obsession' are nominalisations - ideas turned into nouns."),
     ("It would seem that constant busyness has become a badge of honour.", "'It would seem that' is cautious, hedged language."),
     ("Yet the pursuit of stillness is arguably just as productive.", "'Arguably' softens the claim - typical C1 hedging."),
     ("Research suggests that brief pauses can enhance both focus and creativity.", "'Research suggests' attributes the idea rather than stating it as fact."),
     ("Perhaps the real challenge lies not in doing more, but in doing less, deliberately.", "'Not in ... but in ...' balances two contrasting ideas."),
     ("When did you last allow yourself to simply pause?", "A reflective question to the listener."),
   ],
   checks=[
     dict(q="What has become 'a badge of honour', according to the host?", why="Line 3 says 'constant busyness has become a badge of honour.'",
       opts=[("Constant busyness", True, "Yes - being always busy."),
             ("Getting enough sleep", False, "No, the host means busyness."),
             ("Slowing down", False, "The host argues that this is undervalued.")]),
     dict(q="What does research suggest brief pauses can do?", why="Line 5 says pauses 'can enhance both focus and creativity.'",
       opts=[("Enhance focus and creativity", True, "Correct."),
             ("Waste valuable time", False, "No, the opposite."),
             ("Cause more stress", False, "The podcast says they help.")]),
   ]),
 dict(level="C1", k="0110", title="Cities of Tomorrow", theme="urban life and sustainability",
   about="The host examines how cities are evolving, practising discourse markers and cohesive devices from C1.",
   lines=[
     ("Welcome back to the Ratel English podcast.", "A greeting for returning listeners."),
     ("Cities today face an unprecedented set of pressures.", "'Unprecedented' means never seen before."),
     ("On the one hand, they drive innovation and opportunity.", "'On the one hand' opens one side of a contrast."),
     ("On the other, they consume vast resources and generate enormous waste.", "'On the other' completes the contrast."),
     ("Consequently, urban planners are rethinking everything from transport to green space.", "'Consequently' signals a result."),
     ("Furthermore, the most liveable cities tend to be those that put people, not cars, first.", "'Furthermore' adds a related point."),
     ("What would make your own city more liveable?", "A question inviting the listener's view."),
   ],
   checks=[
     dict(q="According to the host, what are the most liveable cities like?", why="Line 6 says they 'put people, not cars, first.'",
       opts=[("They put people before cars", True, "Yes - people first."),
             ("They have the tallest buildings", False, "No, that is not mentioned."),
             ("They ban all transport", False, "The podcast says rethink transport, not ban it.")]),
     dict(q="Why are urban planners rethinking cities?", why="Lines 4-5: cities consume resources and generate waste, so ('consequently') planners rethink them.",
       opts=[("Because cities consume resources and create waste", True, "Correct - that is the pressure."),
             ("Because cities are shrinking", False, "No, they face growth pressures."),
             ("Because no one lives in them", False, "The opposite is true.")]),
   ]),
 dict(level="C2", k="0111", title="The Paradox of Choice", theme="psychology and decision-making",
   about="The host explores why more options can mean less satisfaction, using the nuanced, abstract register of C2.",
   lines=[
     ("Hello, and welcome to the Ratel English podcast.", "A standard opening greeting."),
     ("We tend to assume that the more choices we have, the freer and happier we must be.", "'The more ..., the ...' links two rising ideas."),
     ("Counterintuitively, an abundance of options can leave us paralysed rather than liberated.", "'Counterintuitively' flags a surprising, against-expectation point."),
     ("Faced with endless alternatives, we second-guess ourselves and savour our decisions less.", "The opening phrase compresses 'when we are faced with ...'."),
     ("Had we been offered fewer options, we might paradoxically have felt more content.", "'Had we been ...' is an inverted third conditional, a formal C2 structure."),
     ("This is not to romanticise scarcity, but to question our reflexive worship of choice.", "'This is not to ..., but to ...' pre-empts a misreading."),
     ("Where in your own life might less actually be more?", "A reflective, paradoxical question to the listener."),
   ],
   checks=[
     dict(q="What can 'an abundance of options' lead to, according to the host?", why="Line 3 says it 'can leave us paralysed rather than liberated.'",
       opts=[("Feeling paralysed rather than free", True, "Yes - that is the paradox."),
             ("Greater happiness always", False, "No, that is the assumption the host challenges."),
             ("Faster decisions", False, "The opposite - we second-guess ourselves.")]),
     dict(q="What is the host's main point?", why="Line 6 says the aim is 'to question our reflexive worship of choice.'",
       opts=[("We should question our worship of choice", True, "Correct - a nuanced take."),
             ("Scarcity is always better", False, "No, the host avoids romanticising scarcity."),
             ("Choice is meaningless", False, "The host is more nuanced than that.")]),
   ]),
 dict(level="C2", k="0112", title="On the Limits of Language", theme="philosophy and communication",
   about="The host muses on what language can and cannot capture, showcasing the sophisticated, idiomatic control expected at C2.",
   lines=[
     ("Welcome back to the Ratel English podcast.", "A greeting for returning listeners."),
     ("For all its richness, language is a famously blunt instrument for conveying inner experience.", "'For all its richness' concedes a point before contrasting it."),
     ("There are shades of feeling that slip through the net of even the most precise vocabulary.", "'Slip through the net' is an idiom meaning to escape or be missed."),
     ("We reach for metaphor precisely because the literal so often falls short.", "'Falls short' means fails to be enough."),
     ("And yet, it is in that very struggle to articulate the ineffable that literature and poetry are born.", "A cleft structure ('it is ... that ...') for emphasis; 'ineffable' means beyond words."),
     ("Perhaps meaning resides less in the words themselves than in the spaces between them.", "'Less in ... than in ...' weighs one idea against another."),
     ("What have you ever felt but found impossible to put into words?", "A reflective question to the listener."),
   ],
   checks=[
     dict(q="Why do we 'reach for metaphor', according to the host?", why="Line 4 says it is 'because the literal so often falls short.'",
       opts=[("Because literal language often falls short", True, "Yes - metaphor fills the gap."),
             ("Because metaphors are easier", False, "No, that is not the reason given."),
             ("Because words are meaningless", False, "The host is more subtle than that.")]),
     dict(q="Where does the host suggest meaning may reside?", why="Line 6 says meaning may reside 'in the spaces between' the words.",
       opts=[("In the spaces between words", True, "Correct - between the words."),
             ("Only in the dictionary", False, "No, the opposite idea."),
             ("Nowhere at all", False, "The host does not deny meaning.")]),
   ]),
]
