# -*- coding: utf-8 -*-
# Opus 4.8-authored story specs for the Stories / Read&Listen wave (2 per level,
# A1->C2). Kept compact; ratel-tools/gen_stories_wave.py expands them into
# schema-correct passage/sentence/item/gloss rows. audio_ref left null.
STORIES = [
 dict(level="A1", k="0101", title="Anna's New Cat", theme="pets and home",
   about="A simple present-simple story practising he/she/it verbs and this/her from Unit 1.",
   lines=[
     ("Anna has a new cat.", "'Has' is the present of 'have' for he, she, and it."),
     ("The cat is small and grey.", "'Is' describes one thing: the cat."),
     ("It sleeps on Anna's bed.", "For he/she/it we add -s: sleep becomes sleeps."),
     ("Anna gives it milk every day.", "'Every day' tells us this happens all the time."),
     ("She loves her little cat.", "'Her' shows the cat belongs to Anna."),
   ],
   checks=[
     dict(q="What colour is the cat?", why="Line 2 says the cat is small and grey.",
       opts=[("Grey", True, "Yes - the story says the cat is small and grey."),
             ("Black", False, "No, the cat is grey, not black."),
             ("White", False, "No, the cat is grey, not white.")]),
     dict(q="Where does the cat sleep?", why="Line 3 says it sleeps on Anna's bed.",
       opts=[("On Anna's bed", True, "Right - 'It sleeps on Anna's bed.'"),
             ("On the floor", False, "The story does not mention the floor."),
             ("Outside", False, "The cat sleeps on the bed, not outside.")]),
   ]),
 dict(level="A1", k="0102", title="At the Market", theme="food and shopping",
   about="Everyday shopping vocabulary with present simple and numbers.",
   lines=[
     ("Tom goes to the market on Monday.", "'Goes' is the he/she/it form of 'go'."),
     ("He wants apples and bread.", "'Wants' adds -s because 'he' is one person."),
     ("The apples are two dollars.", "'Are' is used with a plural: the apples."),
     ("Tom buys four red apples.", "The adjective 'red' comes before the noun 'apples'."),
     ("He says thank you and goes home.", "'Goes home' means returns to his house."),
   ],
   checks=[
     dict(q="What day does Tom go to the market?", why="Line 1 says Tom goes on Monday.",
       opts=[("Monday", True, "Yes - 'Tom goes to the market on Monday.'"),
             ("Sunday", False, "The story says Monday, not Sunday."),
             ("Friday", False, "No, it is Monday.")]),
     dict(q="How many apples does Tom buy?", why="Line 4 says he buys four red apples.",
       opts=[("Four", True, "Correct - he buys four red apples."),
             ("Two", False, "Two is the price in dollars, not the number of apples."),
             ("Ten", False, "The story says four.")]),
   ]),
 dict(level="A2", k="0101", title="A Rainy Saturday", theme="weather and plans",
   about="A past-simple story about changing plans because of the weather.",
   lines=[
     ("Last Saturday, it rained all day.", "'Rained' is the past simple of 'rain'."),
     ("Maria wanted to go to the park, but she stayed home.", "'But' joins two contrasting ideas."),
     ("She watched two films and made hot soup.", "'Made' is the irregular past of 'make'."),
     ("In the afternoon, her friend Lucy called her.", "'Called' is a regular past-simple verb."),
     ("They played a card game online together.", "'Together' shows they did it as a pair."),
     ("It was a quiet but happy day.", "'Was' is the past of 'is'."),
   ],
   checks=[
     dict(q="Why did Maria stay home?", why="It rained all day, so she stayed home instead of the park.",
       opts=[("Because it rained", True, "Yes - it rained all day."),
             ("Because she was ill", False, "The story does not say she was ill."),
             ("Because the park was closed", False, "The reason given is the rain.")]),
     dict(q="What did Maria and Lucy do together?", why="Line 5 says they played a card game online.",
       opts=[("Played a card game online", True, "Correct - they played online together."),
             ("Went to the cinema", False, "Maria watched films at home, not the cinema."),
             ("Cooked dinner", False, "Maria made soup alone, before Lucy called.")]),
   ]),
 dict(level="A2", k="0102", title="The Lost Key", theme="home and problems",
   about="A short past-simple story about solving an everyday problem at home.",
   lines=[
     ("Yesterday, David could not find his house key.", "'Could not' is the past of 'cannot'."),
     ("He looked under the sofa and behind the door.", "'Under' and 'behind' show position."),
     ("His sister Emma helped him search every room.", "'Helped' is a regular past-simple verb."),
     ("Finally, they found the key inside his coat pocket.", "'Found' is the irregular past of 'find'."),
     ("David felt happy and a little silly.", "'Felt' is the past of 'feel'."),
     ("Now he always keeps the key in the same place.", "'Now' returns us to the present simple."),
   ],
   checks=[
     dict(q="Where was the key in the end?", why="Line 4 says they found it inside his coat pocket.",
       opts=[("In his coat pocket", True, "Yes - the key was inside his coat pocket."),
             ("Under the sofa", False, "He looked there but did not find it."),
             ("Behind the door", False, "He checked there too, with no luck.")]),
     dict(q="Who helped David look for the key?", why="Line 3 says his sister Emma helped him.",
       opts=[("His sister Emma", True, "Correct - Emma helped him search."),
             ("His mother", False, "The story mentions his sister, not his mother."),
             ("Nobody", False, "Emma helped him search every room.")]),
   ]),
 dict(level="B1", k="0101", title="The Job Interview", theme="work and experience",
   about="A narrative practising the present perfect and past perfect around a first interview.",
   lines=[
     ("Sofia had never been to a job interview before.", "'Had never been' = past perfect for an experience before another past moment."),
     ("She had prepared her answers all week, but she still felt nervous.", "'Had prepared' happened before she felt nervous."),
     ("When she arrived, the manager smiled and offered her a coffee.", "Two past-simple actions in sequence."),
     ("They talked about her experience and the skills she had learned at university.", "'Had learned' points back to an earlier time."),
     ("Sofia explained that she had already worked on two small projects.", "'Had already worked' stresses completion before now."),
     ("By the end, she felt confident, and the manager promised to call her soon.", "'By the end' marks the result of the meeting."),
     ("Two days later, she got the job.", "The simple past closes the story."),
   ],
   checks=[
     dict(q="How did Sofia feel at the start of the interview?", why="Line 2 says she still felt nervous despite preparing.",
       opts=[("Nervous", True, "Yes - she felt nervous even though she had prepared."),
             ("Bored", False, "The story never says she was bored."),
             ("Angry", False, "There is no anger in the story.")]),
     dict(q="What did the manager promise at the end?", why="Line 6 says the manager promised to call her soon.",
       opts=[("To call her soon", True, "Correct - the manager promised to call soon."),
             ("To raise her salary", False, "Salary is not mentioned."),
             ("To give her a coffee", False, "The coffee came at the start, not as a promise.")]),
   ]),
 dict(level="B1", k="0102", title="A Trip to Remember", theme="travel and choices",
   about="A travel narrative mixing the past simple with a third conditional.",
   lines=[
     ("During the summer, Leo travelled to a small town by the sea.", "'Travelled' sets the story in the past."),
     ("He had planned to relax, but he ended up exploring every day.", "'Had planned' happened before the trip itself."),
     ("One morning, he met a fisherman who offered to take him out on his boat.", "A relative clause: 'who offered...' describes the fisherman."),
     ("If Leo had said no, he would have missed the best day of his trip.", "Third conditional: an imagined past that did not happen."),
     ("They watched dolphins jump beside the boat as the sun rose.", "'As' shows two things happening at the same time."),
     ("Leo took hundreds of photos, but he knew the real memory was in his heart.", "'But' contrasts the photos with the true memory."),
   ],
   checks=[
     dict(q="What did the fisherman offer Leo?", why="Line 3 says he offered to take Leo out on his boat.",
       opts=[("A trip on his boat", True, "Yes - the fisherman offered a boat trip."),
             ("A place to stay", False, "Accommodation is not mentioned."),
             ("A job", False, "No job is offered in the story.")]),
     dict(q="What did they see beside the boat?", why="Line 5 says they watched dolphins jump beside the boat.",
       opts=[("Dolphins", True, "Correct - they watched dolphins jump."),
             ("Whales", False, "The story mentions dolphins, not whales."),
             ("Nothing", False, "They clearly saw dolphins.")]),
   ]),
 dict(level="B2", k="0101", title="The Misunderstanding", theme="friendship and communication",
   about="An upper-intermediate narrative built on the past perfect and reported speech.",
   lines=[
     ("Nadia was sure that her friend Omar had forgotten her birthday.", "'Had forgotten' = something before the main past moment."),
     ("He had not called, and he had not sent a single message all morning.", "Repeated past perfect stresses the absence of contact."),
     ("She told herself that she did not care, although the silence hurt.", "'Although' concedes a contrasting truth."),
     ("That evening, when she opened her front door, the lights suddenly came on.", "A time clause with 'when' frames the surprise."),
     ("Omar and a dozen friends shouted that they had been planning the surprise for weeks.", "Reported speech with the past perfect continuous."),
     ("Nadia realised she had judged him far too quickly.", "'Had judged' looks back on her earlier mistake."),
     ("Sometimes the people who seem to forget are the ones planning something unforgettable.", "A general reflection closes the story."),
   ],
   checks=[
     dict(q="Why did Nadia think Omar had forgotten her birthday?", why="Lines 1-2: he had not called or messaged all morning.",
       opts=[("He had not called or messaged", True, "Yes - his silence made her assume he forgot."),
             ("He told her he forgot", False, "He never said that; she assumed it."),
             ("He was away on holiday", False, "The story does not mention a holiday.")]),
     dict(q="What had Omar actually been doing?", why="Line 5: he and friends had been planning a surprise for weeks.",
       opts=[("Planning a surprise party", True, "Correct - they had planned it for weeks."),
             ("Ignoring her on purpose", False, "The opposite - he was preparing a surprise."),
             ("Working late", False, "Work is not the reason for his silence.")]),
     dict(q="What lesson does the final line suggest?", why="The closing reflection warns against judging people too quickly.",
       opts=[("Do not judge people too quickly", True, "Yes - appearances can mislead."),
             ("Always plan ahead", False, "That is not the story's point."),
             ("Birthdays are unimportant", False, "The story values the friendship, not this idea.")]),
   ]),
 dict(level="B2", k="0102", title="Working From Home", theme="modern work and balance",
   about="An opinion-style narrative rich in linking devices (on the one hand, as a result).",
   lines=[
     ("When Priya first started working from home, she thought it would be easy.", "A time clause sets up an expectation that will be challenged."),
     ("In reality, the line between work and rest quickly began to blur.", "'In reality' signals a contrast with the expectation."),
     ("On the one hand, she saved two hours of commuting every day.", "'On the one hand' introduces one side of an argument."),
     ("On the other hand, she often found herself answering emails late at night.", "'On the other hand' introduces the opposing side."),
     ("To solve this, she set strict hours and took a walk each afternoon.", "'To solve this' introduces her purpose."),
     ("As a result, she became both more productive and far less stressed.", "'As a result' introduces a consequence."),
     ("She now believes that freedom at work only helps if you build your own structure.", "The conclusion states her considered opinion."),
   ],
   checks=[
     dict(q="What problem did Priya face working from home?", why="Line 2: work and rest began to blur together.",
       opts=[("Work and rest blurred together", True, "Yes - the boundary between them disappeared."),
             ("Her internet was too slow", False, "Technology is not mentioned."),
             ("She missed her salary", False, "Money is not the issue here.")]),
     dict(q="How did she solve the problem?", why="Line 5: she set strict hours and took a daily walk.",
       opts=[("Strict hours and a daily walk", True, "Correct - structure and a break each afternoon."),
             ("She returned to the office", False, "She stayed home but added structure."),
             ("She stopped checking email", False, "She limited the hours, not email entirely.")]),
     dict(q="What is Priya's final opinion?", why="Line 7: freedom helps only with self-built structure.",
       opts=[("Freedom needs self-made structure", True, "Yes - that is her conclusion."),
             ("Working from home is always easy", False, "She found it harder than expected."),
             ("Commuting is better", False, "She valued saving the commute.")]),
   ]),
 dict(level="C1", k="0101", title="The Old Bookshop", theme="memory and change",
   about="An advanced narrative using cleft sentences and inversion for emphasis.",
   lines=[
     ("It was in a narrow street, half-forgotten by the city, that the old bookshop had stood for sixty years.", "A cleft sentence ('It was... that...') foregrounds the place."),
     ("What drew people in was not its stock but its owner, a woman who seemed to know exactly which book each visitor needed.", "A 'what'-cleft shifts focus onto the owner."),
     ("Never had Marcus expected a shop to change the course of his life.", "Inversion after 'never' adds dramatic emphasis."),
     ("Yet a single novel she pressed into his hands rekindled an ambition he had long abandoned.", "'Rekindled' and 'long abandoned' compress a whole backstory."),
     ("Within a year, he had left his office job to write full-time.", "The past perfect marks the completed change."),
     ("When the shop finally closed, he understood that some places matter less for what they sell than for what they awaken.", "'less for... than for...' balances two ideas."),
     ("He kept that novel on his desk, a reminder of the afternoon everything quietly shifted.", "An appositive phrase adds a reflective image."),
   ],
   checks=[
     dict(q="According to the story, what made the bookshop special?", why="Line 2 (a cleft) says it was the owner, not the stock.",
       opts=[("Its owner, who knew what each visitor needed", True, "Yes - the 'what'-cleft foregrounds the owner."),
             ("Its very low prices", False, "Prices are never mentioned."),
             ("Its large size", False, "The shop is on a narrow, forgotten street.")]),
     dict(q="How did the shop change Marcus's life?", why="Lines 4-5: a novel revived his ambition and he became a full-time writer.",
       opts=[("It revived his ambition to write", True, "Correct - he left his job to write."),
             ("It gave him a job in the shop", False, "He left his office job to write, not to work there."),
             ("It taught him to run a business", False, "That is not what the story describes.")]),
     dict(q="What does the narrator conclude about such places?", why="Line 6: they matter for what they awaken, not what they sell.",
       opts=[("They matter for what they awaken", True, "Yes - meaning over merchandise."),
             ("They should never close", False, "The story accepts the closure calmly."),
             ("They are only about money", False, "The narrator argues the opposite.")]),
   ]),
 dict(level="C1", k="0102", title="A Difficult Decision", theme="ambition and loyalty",
   about="A reflective narrative using hedging language and inverted conditionals.",
   lines=[
     ("Elena had been offered a promotion that would double her salary but move her a thousand miles from her ageing parents.", "The relative clause lays out the dilemma."),
     ("It might have seemed an obvious choice, were it not for the promise she had once made to them.", "'Were it not for' is a formal inverted conditional."),
     ("She weighed ambition against loyalty, aware that whichever path she chose would carry a quiet cost.", "'Whichever' concedes that both options cost something."),
     ("Friends suggested she could always fly back on weekends, though she suspected such visits would grow rare.", "Hedging ('suspected', 'would grow') softens the claim."),
     ("In the end, she turned the offer down, not out of fear, but out of a clear sense of what mattered most.", "'Not out of... but out of...' clarifies her motive."),
     ("Some might call it a wasted opportunity; she preferred to call it a considered one.", "The contrast reframes the decision positively."),
   ],
   checks=[
     dict(q="What made the promotion difficult to accept?", why="Line 1: it would move her far from her ageing parents.",
       opts=[("It would move her far from her parents", True, "Yes - distance from family was the cost."),
             ("The salary was too low", False, "It would have doubled her salary."),
             ("She disliked the new role", False, "Her doubt was about family, not the job.")]),
     dict(q="What did Elena finally decide?", why="Line 5: she turned the offer down.",
       opts=[("She turned the offer down", True, "Correct - she declined the promotion."),
             ("She accepted and moved", False, "She chose not to move."),
             ("She asked to delay it a year", False, "No delay is mentioned; she declined.")]),
     dict(q="How does Elena view her own decision?", why="Line 6: she calls it considered, not wasted.",
       opts=[("As considered, not wasted", True, "Yes - she reframes it as deliberate."),
             ("As a mistake she regrets", False, "She does not express regret."),
             ("As forced upon her", False, "She made the choice freely.")]),
   ]),
 dict(level="C2", k="0101", title="The Art of Persuasion", theme="rhetoric and influence",
   about="A mastery-level portrait using idiom, balanced clauses and understatement.",
   lines=[
     ("Few speakers command a room the way Professor Adeyemi did, and fewer still made it look so effortless.", "'Few... fewer still' is an emphatic comparative pattern."),
     ("It was not grand gestures but the well-placed pause that held his audiences spellbound.", "A cleft plus 'not... but...' pinpoints the real cause."),
     ("He understood, as the finest orators do, that persuasion rarely hinges on the loudest argument.", "The parenthetical 'as the finest orators do' adds authority."),
     ("Rather, it is the speaker who listens most closely who ends up being heard.", "A paradox delivered through a double relative clause."),
     ("Where others hammered their points home, Adeyemi planted a question and let it take root.", "The metaphor contrasts force with cultivation."),
     ("By the time he reached his conclusion, the audience felt they had arrived there of their own accord.", "'Of their own accord' = without being pushed."),
     ("That, he would say with a knowing smile, is the whole art: to convince people they were never being persuaded at all.", "The closing line states the story's central irony."),
   ],
   checks=[
     dict(q="What held Adeyemi's audiences spellbound?", why="Line 2: not grand gestures but the well-placed pause.",
       opts=[("The well-placed pause", True, "Yes - the cleft foregrounds the pause, not gestures."),
             ("His loud, forceful voice", False, "The story praises quiet control, not volume."),
             ("Elaborate slides", False, "No visual aids are mentioned.")]),
     dict(q="According to the passage, who ends up being heard?", why="Line 4: the speaker who listens most closely.",
       opts=[("The speaker who listens most closely", True, "Correct - that is the story's paradox."),
             ("The speaker who talks the most", False, "The passage argues the opposite."),
             ("The most senior speaker", False, "Seniority is not the point.")]),
     dict(q="What does Adeyemi consider the whole art of persuasion?", why="Line 7: making people feel they were never persuaded at all.",
       opts=[("Making people feel they arrived at the idea themselves", True, "Yes - persuasion that hides its own hand."),
             ("Overwhelming people with facts", False, "He avoids hammering points home."),
             ("Speaking longer than anyone else", False, "Length is not his method.")]),
   ]),
 dict(level="C2", k="0102", title="Between the Lines", theme="literature and interpretation",
   about="A mastery-level classroom scene about how meaning is co-created by the reader.",
   lines=[
     ("The poem was barely twelve lines long, yet the class had argued over it for the better part of an hour.", "'Yet' concedes a surprising contrast; 'the better part of' is idiomatic."),
     ("Half insisted it was about grief; the rest were equally certain it concerned nothing more than a walk in the rain.", "Balanced clauses set two readings against each other."),
     ("Their teacher, who had said remarkably little, finally observed that both camps might be missing the point.", "The understatement 'remarkably little' heightens her authority."),
     ("A poem, she suggested, is less a locked door to be opened than a mirror held up to the reader.", "An extended metaphor reframes the whole debate."),
     ("What each student had found in those lines said as much about them as about the poet.", "A 'what'-cleft delivers the story's thesis."),
     ("The room fell quiet, not from confusion, but from the discomfort of a truth landing squarely.", "'Not from... but from...' distinguishes two kinds of silence."),
     ("It was then that the loudest sceptic admitted, almost reluctantly, that she had been reading her own story all along.", "A cleft plus hedged verb marks her concession."),
     ("They left the class certain of far less than when they had entered, and somehow the better for it.", "The paradox ('certain of less... the better for it') closes the piece."),
   ],
   checks=[
     dict(q="Why had the class argued for nearly an hour?", why="Lines 1-2: they disagreed over what the short poem meant.",
       opts=[("They disagreed about the poem's meaning", True, "Yes - grief versus a simple walk in the rain."),
             ("The poem was extremely long", False, "It was barely twelve lines."),
             ("They disliked the poet", False, "Their dispute was about meaning, not the poet.")]),
     dict(q="What did the teacher compare a poem to?", why="Line 4: a mirror held up to the reader, not a locked door.",
       opts=[("A mirror held up to the reader", True, "Correct - meaning reflects the reader."),
             ("A locked door to be opened", False, "She explicitly rejects that image."),
             ("A puzzle with one solution", False, "Her point is that meaning is not fixed.")]),
     dict(q="What did the sceptic finally admit?", why="Line 7: she had been reading her own story into the poem.",
       opts=[("She had read her own story into it", True, "Yes - proving the teacher's point."),
             ("The poem meant nothing at all", False, "She conceded meaning, not emptiness."),
             ("The teacher was wrong", False, "Her admission supports the teacher.")]),
   ]),
]
