// GENERATED by ratel-tools/codegen_dart.py from schema/ (P0-6). DO NOT EDIT BY HAND.
// Regenerate: python3 ratel-tools/codegen_dart.py && dart run build_runner build

import 'package:json_annotation/json_annotation.dart';

@JsonEnum()
enum CefrLevel {
  @JsonValue('A1') a1,
  @JsonValue('A2') a2,
  @JsonValue('B1') b1,
  @JsonValue('B2') b2,
  @JsonValue('C1') c1,
  @JsonValue('C2') c2;
}

@JsonEnum()
enum CefrCeiling {
  @JsonValue('A2') a2,
  @JsonValue('B1') b1,
  @JsonValue('B2') b2,
  @JsonValue('C2') c2;
}

@JsonEnum()
enum ExerciseType {
  @JsonValue('mcq') mcq,
  @JsonValue('cloze') cloze,
  @JsonValue('translate') translate,
  @JsonValue('listen') listen,
  @JsonValue('word_order') wordOrder,
  @JsonValue('match') match,
  @JsonValue('dictation') dictation,
  @JsonValue('speak') speak,
  @JsonValue('scripted_roleplay') scriptedRoleplay,
  @JsonValue('write') write,
  @JsonValue('live_roleplay') liveRoleplay;
}

@JsonEnum()
enum Pos {
  @JsonValue('noun') noun,
  @JsonValue('verb') verb,
  @JsonValue('adj') adj,
  @JsonValue('adv') adv,
  @JsonValue('pron') pron,
  @JsonValue('det') det,
  @JsonValue('adp') adp,
  @JsonValue('num') num_,
  @JsonValue('conj') conj,
  @JsonValue('cconj') cconj,
  @JsonValue('sconj') sconj,
  @JsonValue('part') part_,
  @JsonValue('intj') intj,
  @JsonValue('propn') propn,
  @JsonValue('aux') aux,
  @JsonValue('sym') sym,
  @JsonValue('punct') punct,
  @JsonValue('x') x;
}

@JsonEnum()
enum DifficultyBand {
  @JsonValue('intro') intro,
  @JsonValue('core') core,
  @JsonValue('stretch') stretch;
}

@JsonEnum()
enum ProvenanceKind {
  @JsonValue('authored') authored,
  @JsonValue('ai_generated') aiGenerated;
}

@JsonEnum()
enum ReviewStatus {
  @JsonValue('draft') draft,
  @JsonValue('auto_certified') autoCertified,
  @JsonValue('needs_review') needsReview,
  @JsonValue('human_reviewed') humanReviewed,
  @JsonValue('retired') retired;
}

@JsonEnum()
enum TtsTier {
  @JsonValue('hd') hd,
  @JsonValue('basic') basic,
  @JsonValue('none') none;
}

@JsonEnum()
enum PronCapability {
  @JsonValue('asr') asr,
  @JsonValue('shadowing') shadowing;
}

@JsonEnum()
enum TextDirection {
  @JsonValue('ltr') ltr,
  @JsonValue('rtl') rtl;
}

@JsonEnum()
enum ItemDirection {
  @JsonValue('l1_to_l2') l1ToL2,
  @JsonValue('l2_to_l1') l2ToL1;
}

@JsonEnum()
enum ContrastType {
  @JsonValue('translate_from_l1') translateFromL1,
  @JsonValue('false_friend') falseFriend,
  @JsonValue('transliteration') transliteration,
  @JsonValue('l1_interference') l1Interference;
}

@JsonEnum()
enum MediaType {
  @JsonValue('audio') audio,
  @JsonValue('image') image,
  @JsonValue('video') video;
}

@JsonEnum()
enum ContentKind {
  @JsonValue('sense') sense,
  @JsonValue('prompt') prompt,
  @JsonValue('hint') hint,
  @JsonValue('grammar_rule') grammarRule,
  @JsonValue('instruction') instruction,
  @JsonValue('rubric') rubric,
  @JsonValue('explanation') explanation;
}

@JsonEnum()
enum PassageKind {
  @JsonValue('story') story,
  @JsonValue('podcast') podcast,
  @JsonValue('video') video;
}

@JsonEnum()
enum ScenarioKind {
  @JsonValue('roleplay') roleplay,
  @JsonValue('adventure') adventure;
}

@JsonEnum()
enum PluralCategory {
  @JsonValue('zero') zero,
  @JsonValue('one') one,
  @JsonValue('two') two,
  @JsonValue('few') few,
  @JsonValue('many') many,
  @JsonValue('other') other;
}

@JsonEnum()
enum UnicodeNorm {
  @JsonValue('NFC') nfc,
  @JsonValue('NFKC') nfkc;
}

@JsonEnum()
enum FsrsState {
  @JsonValue('new') new_,
  @JsonValue('learning') learning,
  @JsonValue('review') review,
  @JsonValue('relearning') relearning;
}

@JsonEnum()
enum LedgerEntryType {
  @JsonValue('grant') grant,
  @JsonValue('spend') spend,
  @JsonValue('refund') refund;
}

@JsonEnum()
enum GrantSource {
  @JsonValue('daily_free') dailyFree,
  @JsonValue('review_free') reviewFree,
  @JsonValue('ad_reward') adReward,
  @JsonValue('purchase') purchase,
  @JsonValue('subscription') subscription,
  @JsonValue('promo') promo,
  @JsonValue('refund_reversal') refundReversal;
}
