// GENERATED by ratel-tools/codegen_dart.py from schema/ (P0-6). DO NOT EDIT BY HAND.
// Regenerate: python3 ratel-tools/codegen_dart.py && dart run build_runner build

import 'package:freezed_annotation/freezed_annotation.dart';
import 'enums.dart';

part 'payloads.freezed.dart';
part 'payloads.g.dart';

@freezed
abstract class NormalizationFlags with _$NormalizationFlags {
  const factory NormalizationFlags({
    @JsonKey(name: 'strip_diacritics') bool? stripDiacritics,
    @JsonKey(name: 'fold_case') bool? foldCase,
    @JsonKey(name: 'accept_kana_for_kanji') bool? acceptKanaForKanji,
    @JsonKey(name: 'ignore_tone_marks') bool? ignoreToneMarks,
    @JsonKey(name: 'collapse_whitespace') bool? collapseWhitespace,
    @JsonKey(name: 'unicode_norm') UnicodeNorm? unicodeNorm,
  }) = _NormalizationFlags;
  factory NormalizationFlags.fromJson(Map<String, dynamic> json) => _$NormalizationFlagsFromJson(json);
}

@freezed
abstract class AnswerSpec with _$AnswerSpec {
  const factory AnswerSpec({
    required List<String> accepted,
    @JsonKey(name: 'normalization_flags') NormalizationFlags? normalizationFlags,
  }) = _AnswerSpec;
  factory AnswerSpec.fromJson(Map<String, dynamic> json) => _$AnswerSpecFromJson(json);
}

@freezed
abstract class Token with _$Token {
  const factory Token({
    required String surface,
    @JsonKey(name: 'lemma_ref') String? lemmaRef,
    String? reading,
    Map<String, Object?>? features,
  }) = _Token;
  factory Token.fromJson(Map<String, dynamic> json) => _$TokenFromJson(json);
}

@freezed
abstract class ScriptMeta with _$ScriptMeta {
  const factory ScriptMeta({
    required String script,
    @JsonKey(name: 'uses_spaces') bool? usesSpaces,
    @JsonKey(name: 'has_grapheme_clusters') bool? hasGraphemeClusters,
  }) = _ScriptMeta;
  factory ScriptMeta.fromJson(Map<String, dynamic> json) => _$ScriptMetaFromJson(json);
}

@freezed
abstract class Provenance with _$Provenance {
  const factory Provenance({
    @JsonKey(name: 'batch_id') required String batchId,
    required ProvenanceKind provenance,
    @JsonKey(name: 'model_version') String? modelVersion,
    @JsonKey(name: 'review_status') required ReviewStatus reviewStatus,
    @JsonKey(name: 'content_version') required int contentVersion,
    @JsonKey(name: 'created_at') required String createdAt,
    @JsonKey(name: 'updated_at') required String updatedAt,
    @JsonKey(name: 'source_attribution') String? sourceAttribution,
  }) = _Provenance;
  factory Provenance.fromJson(Map<String, dynamic> json) => _$ProvenanceFromJson(json);
}
