// GENERATED by ratel-tools/codegen_dart.py from schema/ (P0-6). DO NOT EDIT BY HAND.
// Regenerate: python3 ratel-tools/codegen_dart.py && dart run build_runner build

import 'package:freezed_annotation/freezed_annotation.dart';
import 'enums.dart';
import 'payloads.dart';

part 'tables.freezed.dart';
part 'tables.g.dart';

@freezed
abstract class Sentence with _$Sentence {
  const factory Sentence({
    @JsonKey(name: 'sentence_id') required String sentenceId,
    required String locale,
    @JsonKey(name: 'target_text') required String targetText,
    required List<Token> tokens,
    @JsonKey(name: 'tokens_alt') List<List<Token>>? tokensAlt,
    String? ipa,
    Map<String, Object?>? prosody,
    List<String>? graphemes,
    @JsonKey(name: 'audio_ref') String? audioRef,
    double? difficulty,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    required Provenance provenance,
  }) = _Sentence;
  factory Sentence.fromJson(Map<String, dynamic> json) => _$SentenceFromJson(json);
}

@freezed
abstract class VocabEntry with _$VocabEntry {
  const factory VocabEntry({
    @JsonKey(name: 'vocab_id') required String vocabId,
    required String locale,
    required String lemma,
    required Pos pos,
    @JsonKey(name: 'frequency_rank') int? frequencyRank,
    String? ipa,
    @JsonKey(name: 'audio_ref') String? audioRef,
    @JsonKey(name: 'cefr_level') CefrLevel? cefrLevel,
    required Provenance provenance,
  }) = _VocabEntry;
  factory VocabEntry.fromJson(Map<String, dynamic> json) => _$VocabEntryFromJson(json);
}

@freezed
abstract class Sense with _$Sense {
  const factory Sense({
    @JsonKey(name: 'sense_id') required String senseId,
    @JsonKey(name: 'vocab_id') required String vocabId,
    Pos? pos,
    @JsonKey(name: 'definition_ref') String? definitionRef,
    String? register,
    List<String>? examples,
    @JsonKey(name: 'synset_ref') String? synsetRef,
    required Provenance provenance,
  }) = _Sense;
  factory Sense.fromJson(Map<String, dynamic> json) => _$SenseFromJson(json);
}

@freezed
abstract class GrammarPoint with _$GrammarPoint {
  const factory GrammarPoint({
    @JsonKey(name: 'grammar_id') required String grammarId,
    required String locale,
    required String name,
    @JsonKey(name: 'rule_text_ref') String? ruleTextRef,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    @JsonKey(name: 'unit_id') String? unitId,
    @JsonKey(name: 'lesson_order') int? lessonOrder,
    @JsonKey(name: 'objective_descriptor_ids') List<String>? objectiveDescriptorIds,
    @JsonKey(name: 'concept_refs') List<String>? conceptRefs,
    @JsonKey(name: 'example_refs') List<String>? exampleRefs,
    @JsonKey(name: 'feature_tags') Map<String, Object?>? featureTags,
    required Provenance provenance,
  }) = _GrammarPoint;
  factory GrammarPoint.fromJson(Map<String, dynamic> json) => _$GrammarPointFromJson(json);
}

@freezed
abstract class Phoneme with _$Phoneme {
  const factory Phoneme({
    @JsonKey(name: 'phoneme_id') required String phonemeId,
    required String locale,
    @JsonKey(name: 'ipa_symbol') required String ipaSymbol,
    List<String>? examples,
    Map<String, Object?>? features,
    required Provenance provenance,
  }) = _Phoneme;
  factory Phoneme.fromJson(Map<String, dynamic> json) => _$PhonemeFromJson(json);
}

@freezed
abstract class Item with _$Item {
  const factory Item({
    @JsonKey(name: 'item_id') required String itemId,
    required String locale,
    @JsonKey(name: 'exercise_type') required ExerciseType exerciseType,
    @JsonKey(name: 'enum_version') int? enumVersion,
    @JsonKey(name: 'prompt_ref') required String promptRef,
    @JsonKey(name: 'answer_spec') AnswerSpec? answerSpec,
    List<Map<String, Object?>>? options,
    @JsonKey(name: 'rubric_spec') Map<String, Object?>? rubricSpec,
    @JsonKey(name: 'skill_ids') required List<String> skillIds,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    @JsonKey(name: 'difficulty_band') DifficultyBand? difficultyBand,
    @JsonKey(name: 'irt_a') double? irtA,
    @JsonKey(name: 'irt_b') double? irtB,
    @JsonKey(name: 'irt_c') double? irtC,
    @JsonKey(name: 'difficulty_est') double? difficultyEst,
    @JsonKey(name: 'source_locale') String? sourceLocale,
    @JsonKey(name: 'contrast_type') ContrastType? contrastType,
    ItemDirection? direction,
    required Provenance provenance,
  }) = _Item;
  factory Item.fromJson(Map<String, dynamic> json) => _$ItemFromJson(json);
}

@freezed
abstract class Locale with _$Locale {
  const factory Locale({
    required String code,
    required String name,
    required TextDirection direction,
    @JsonKey(name: 'plural_categories') required List<PluralCategory> pluralCategories,
    @JsonKey(name: 'script_meta') required ScriptMeta scriptMeta,
    @JsonKey(name: 'tts_tier') required TtsTier ttsTier,
    @JsonKey(name: 'pron_tier') required PronCapability pronTier,
    @JsonKey(name: 'pron_method') PronCapability? pronMethod,
    @JsonKey(name: 'cefr_ceiling') CefrCeiling? cefrCeiling,
  }) = _Locale;
  factory Locale.fromJson(Map<String, dynamic> json) => _$LocaleFromJson(json);
}

@freezed
abstract class MediaAsset with _$MediaAsset {
  const factory MediaAsset({
    @JsonKey(name: 'asset_id') required String assetId,
    required MediaType type,
    required String uri,
    String? locale,
    @JsonKey(name: 'voice_id') String? voiceId,
    String? ssml,
    @JsonKey(name: 'tts_tier') TtsTier? ttsTier,
    @JsonKey(name: 'duration_ms') int? durationMs,
    required Provenance provenance,
  }) = _MediaAsset;
  factory MediaAsset.fromJson(Map<String, dynamic> json) => _$MediaAssetFromJson(json);
}

@freezed
abstract class Gloss with _$Gloss {
  const factory Gloss({
    @JsonKey(name: 'content_id') required String contentId,
    @JsonKey(name: 'content_kind') required ContentKind contentKind,
    @JsonKey(name: 'ui_locale') required String uiLocale,
    required String text,
    @JsonKey(name: 'audio_ref') String? audioRef,
    required Provenance provenance,
  }) = _Gloss;
  factory Gloss.fromJson(Map<String, dynamic> json) => _$GlossFromJson(json);
}

@freezed
abstract class Unit with _$Unit {
  const factory Unit({
    @JsonKey(name: 'unit_id') required String unitId,
    required String locale,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    @JsonKey(name: 'section_order') required int sectionOrder,
    @JsonKey(name: 'section_title_ref') required String sectionTitleRef,
    @JsonKey(name: 'unit_order') required int unitOrder,
    @JsonKey(name: 'title_ref') required String titleRef,
    @JsonKey(name: 'guide_ref') String? guideRef,
    @JsonKey(name: 'objective_descriptor_ids') List<String>? objectiveDescriptorIds,
    required Provenance provenance,
  }) = _Unit;
  factory Unit.fromJson(Map<String, dynamic> json) => _$UnitFromJson(json);
}

@freezed
abstract class Passage with _$Passage {
  const factory Passage({
    @JsonKey(name: 'passage_id') required String passageId,
    required String locale,
    required PassageKind kind,
    @JsonKey(name: 'title_ref') required String titleRef,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    String? theme,
    @JsonKey(name: 'collection_id') String? collectionId,
    @JsonKey(name: 'sentence_refs') required List<String> sentenceRefs,
    @JsonKey(name: 'audio_ref') String? audioRef,
    @JsonKey(name: 'video_ref') String? videoRef,
    @JsonKey(name: 'video_prompt') String? videoPrompt,
    @JsonKey(name: 'duration_ms') int? durationMs,
    @JsonKey(name: 'explain_ref') String? explainRef,
    @JsonKey(name: 'check_item_refs') List<String>? checkItemRefs,
    required Provenance provenance,
  }) = _Passage;
  factory Passage.fromJson(Map<String, dynamic> json) => _$PassageFromJson(json);
}

@freezed
abstract class Scenario with _$Scenario {
  const factory Scenario({
    @JsonKey(name: 'scenario_id') required String scenarioId,
    required String locale,
    required ScenarioKind kind,
    @JsonKey(name: 'title_ref') required String titleRef,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    String? world,
    @JsonKey(name: 'goal_ref') required String goalRef,
    @JsonKey(name: 'rubric_ref') String? rubricRef,
    @JsonKey(name: 'skill_ids') List<String>? skillIds,
    required List<Map<String, Object?>> scenes,
    required Provenance provenance,
  }) = _Scenario;
  factory Scenario.fromJson(Map<String, dynamic> json) => _$ScenarioFromJson(json);
}

@freezed
abstract class User with _$User {
  const factory User({
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'created_at') required String createdAt,
    @JsonKey(name: 'updated_at') required String updatedAt,
    @JsonKey(name: 'pro_until') String? proUntil,
    @JsonKey(name: 'fsrs_weights') List<double>? fsrsWeights,
    @JsonKey(name: 'ui_locale') String? uiLocale,
    String? timezone,
    @JsonKey(name: 'daily_goal_xp') int? dailyGoalXp,
  }) = _User;
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}

@freezed
abstract class UserCourse with _$UserCourse {
  const factory UserCourse({
    @JsonKey(name: 'user_course_id') required String userCourseId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'target_locale') required String targetLocale,
    @JsonKey(name: 'ui_locale') String? uiLocale,
    @JsonKey(name: 'theta_per_skill') Map<String, Object?>? thetaPerSkill,
    @JsonKey(name: 'cefr_target') CefrLevel? cefrTarget,
    @JsonKey(name: 'xp_total') int? xpTotal,
    @JsonKey(name: 'lessons_completed') int? lessonsCompleted,
    @JsonKey(name: 'streak_days') int? streakDays,
    @JsonKey(name: 'streak_last_active') String? streakLastActive,
    int? diamonds,
    @JsonKey(name: 'streak_freezes') int? streakFreezes,
    @JsonKey(name: 'created_at') required String createdAt,
    @JsonKey(name: 'updated_at') required String updatedAt,
  }) = _UserCourse;
  factory UserCourse.fromJson(Map<String, dynamic> json) => _$UserCourseFromJson(json);
}

@freezed
abstract class UserItemState with _$UserItemState {
  const factory UserItemState({
    @JsonKey(name: 'user_item_state_id') required String userItemStateId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'item_id') required String itemId,
    double? stability,
    double? difficulty,
    required String due,
    @JsonKey(name: 'last_review') String? lastReview,
    int? reps,
    int? lapses,
    @JsonKey(name: 'scheduled_days') int? scheduledDays,
    required FsrsState state,
    @JsonKey(name: 'created_at') required String createdAt,
    @JsonKey(name: 'updated_at') required String updatedAt,
  }) = _UserItemState;
  factory UserItemState.fromJson(Map<String, dynamic> json) => _$UserItemStateFromJson(json);
}

@freezed
abstract class UserPhonemeState with _$UserPhonemeState {
  const factory UserPhonemeState({
    @JsonKey(name: 'user_phoneme_state_id') required String userPhonemeStateId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'phoneme_id') required String phonemeId,
    String? locale,
    double? mastery,
    int? attempts,
    @JsonKey(name: 'last_score') double? lastScore,
    String? due,
    @JsonKey(name: 'created_at') required String createdAt,
    @JsonKey(name: 'updated_at') required String updatedAt,
  }) = _UserPhonemeState;
  factory UserPhonemeState.fromJson(Map<String, dynamic> json) => _$UserPhonemeStateFromJson(json);
}

@freezed
abstract class PlacementSession with _$PlacementSession {
  const factory PlacementSession({
    @JsonKey(name: 'placement_session_id') required String placementSessionId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'target_locale') required String targetLocale,
    @JsonKey(name: 'started_at') required String startedAt,
    @JsonKey(name: 'completed_at') String? completedAt,
    @JsonKey(name: 'theta_estimate') double? thetaEstimate,
    @JsonKey(name: 'se_estimate') double? seEstimate,
    @JsonKey(name: 'items_administered') int? itemsAdministered,
    @JsonKey(name: 'result_cefr') CefrLevel? resultCefr,
    List<Map<String, Object?>>? responses,
    @JsonKey(name: 'created_at') String? createdAt,
  }) = _PlacementSession;
  factory PlacementSession.fromJson(Map<String, dynamic> json) => _$PlacementSessionFromJson(json);
}

@freezed
abstract class ReviewLog with _$ReviewLog {
  const factory ReviewLog({
    @JsonKey(name: 'review_log_id') required String reviewLogId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'item_id') required String itemId,
    @JsonKey(name: 'reviewed_at') required String reviewedAt,
    required int rating,
    FsrsState? state,
    @JsonKey(name: 'elapsed_days') int? elapsedDays,
    @JsonKey(name: 'scheduled_days') int? scheduledDays,
    @JsonKey(name: 'stability_after') double? stabilityAfter,
    @JsonKey(name: 'difficulty_after') double? difficultyAfter,
    @JsonKey(name: 'duration_ms') int? durationMs,
  }) = _ReviewLog;
  factory ReviewLog.fromJson(Map<String, dynamic> json) => _$ReviewLogFromJson(json);
}

@freezed
abstract class CreditLedger with _$CreditLedger {
  const factory CreditLedger({
    @JsonKey(name: 'credit_ledger_id') required String creditLedgerId,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'entry_type') required LedgerEntryType entryType,
    required int amount,
    @JsonKey(name: 'balance_after') int? balanceAfter,
    @JsonKey(name: 'grant_source') GrantSource? grantSource,
    @JsonKey(name: 'client_event_id') required String clientEventId,
    @JsonKey(name: 'related_ledger_id') String? relatedLedgerId,
    String? reason,
    @JsonKey(name: 'created_at') required String createdAt,
  }) = _CreditLedger;
  factory CreditLedger.fromJson(Map<String, dynamic> json) => _$CreditLedgerFromJson(json);
}
