// GENERATED by ratel-tools/codegen_dart.py from schema/ (P0-6). DO NOT EDIT BY HAND.
// Regenerate: python3 ratel-tools/codegen_dart.py && dart run build_runner build

import 'package:freezed_annotation/freezed_annotation.dart';
import 'enums.dart';
import 'payloads.dart';

part 'tables.freezed.dart';
part 'tables.g.dart';

@freezed
abstract class Sentence with _$Sentence {
  const factory Sentence({
    @JsonKey(name: 'sentence_id') required String sentenceId,
    required String locale,
    @JsonKey(name: 'target_text') required String targetText,
    required List<Token> tokens,
    @JsonKey(name: 'tokens_alt') List<List<Token>>? tokensAlt,
    String? ipa,
    Map<String, Object?>? prosody,
    List<String>? graphemes,
    @JsonKey(name: 'audio_ref') String? audioRef,
    double? difficulty,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    required Provenance provenance,
  }) = _Sentence;
  factory Sentence.fromJson(Map<String, dynamic> json) => _$SentenceFromJson(json);
}

@freezed
abstract class VocabEntry with _$VocabEntry {
  const factory VocabEntry({
    @JsonKey(name: 'vocab_id') required String vocabId,
    required String locale,
    required String lemma,
    required Pos pos,
    @JsonKey(name: 'frequency_rank') int? frequencyRank,
    String? ipa,
    @JsonKey(name: 'audio_ref') String? audioRef,
    @JsonKey(name: 'cefr_level') CefrLevel? cefrLevel,
    required Provenance provenance,
  }) = _VocabEntry;
  factory VocabEntry.fromJson(Map<String, dynamic> json) => _$VocabEntryFromJson(json);
}

@freezed
abstract class Sense with _$Sense {
  const factory Sense({
    @JsonKey(name: 'sense_id') required String senseId,
    @JsonKey(name: 'vocab_id') required String vocabId,
    Pos? pos,
    @JsonKey(name: 'definition_ref') String? definitionRef,
    String? register,
    List<String>? examples,
    @JsonKey(name: 'synset_ref') String? synsetRef,
    required Provenance provenance,
  }) = _Sense;
  factory Sense.fromJson(Map<String, dynamic> json) => _$SenseFromJson(json);
}

@freezed
abstract class GrammarPoint with _$GrammarPoint {
  const factory GrammarPoint({
    @JsonKey(name: 'grammar_id') required String grammarId,
    required String locale,
    required String name,
    @JsonKey(name: 'rule_text_ref') String? ruleTextRef,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    @JsonKey(name: 'concept_refs') List<String>? conceptRefs,
    @JsonKey(name: 'example_refs') List<String>? exampleRefs,
    @JsonKey(name: 'feature_tags') Map<String, Object?>? featureTags,
    required Provenance provenance,
  }) = _GrammarPoint;
  factory GrammarPoint.fromJson(Map<String, dynamic> json) => _$GrammarPointFromJson(json);
}

@freezed
abstract class Phoneme with _$Phoneme {
  const factory Phoneme({
    @JsonKey(name: 'phoneme_id') required String phonemeId,
    required String locale,
    @JsonKey(name: 'ipa_symbol') required String ipaSymbol,
    List<String>? examples,
    Map<String, Object?>? features,
    required Provenance provenance,
  }) = _Phoneme;
  factory Phoneme.fromJson(Map<String, dynamic> json) => _$PhonemeFromJson(json);
}

@freezed
abstract class Item with _$Item {
  const factory Item({
    @JsonKey(name: 'item_id') required String itemId,
    required String locale,
    @JsonKey(name: 'exercise_type') required ExerciseType exerciseType,
    @JsonKey(name: 'enum_version') int? enumVersion,
    @JsonKey(name: 'prompt_ref') required String promptRef,
    @JsonKey(name: 'answer_spec') AnswerSpec? answerSpec,
    @JsonKey(name: 'skill_ids') required List<String> skillIds,
    @JsonKey(name: 'cefr_level') required CefrLevel cefrLevel,
    @JsonKey(name: 'difficulty_band') DifficultyBand? difficultyBand,
    @JsonKey(name: 'irt_a') double? irtA,
    @JsonKey(name: 'irt_b') double? irtB,
    @JsonKey(name: 'irt_c') double? irtC,
    @JsonKey(name: 'difficulty_est') double? difficultyEst,
    @JsonKey(name: 'source_locale') String? sourceLocale,
    @JsonKey(name: 'contrast_type') ContrastType? contrastType,
    ItemDirection? direction,
    required Provenance provenance,
  }) = _Item;
  factory Item.fromJson(Map<String, dynamic> json) => _$ItemFromJson(json);
}

@freezed
abstract class Locale with _$Locale {
  const factory Locale({
    required String code,
    required String name,
    required TextDirection direction,
    @JsonKey(name: 'plural_categories') required List<PluralCategory> pluralCategories,
    @JsonKey(name: 'script_meta') required ScriptMeta scriptMeta,
    @JsonKey(name: 'tts_tier') required TtsTier ttsTier,
    @JsonKey(name: 'pron_tier') required PronCapability pronTier,
    @JsonKey(name: 'pron_method') PronCapability? pronMethod,
    @JsonKey(name: 'cefr_ceiling') CefrCeiling? cefrCeiling,
  }) = _Locale;
  factory Locale.fromJson(Map<String, dynamic> json) => _$LocaleFromJson(json);
}

@freezed
abstract class MediaAsset with _$MediaAsset {
  const factory MediaAsset({
    @JsonKey(name: 'asset_id') required String assetId,
    required MediaType type,
    required String uri,
    String? locale,
    @JsonKey(name: 'voice_id') String? voiceId,
    String? ssml,
    @JsonKey(name: 'tts_tier') TtsTier? ttsTier,
    @JsonKey(name: 'duration_ms') int? durationMs,
    required Provenance provenance,
  }) = _MediaAsset;
  factory MediaAsset.fromJson(Map<String, dynamic> json) => _$MediaAssetFromJson(json);
}

@freezed
abstract class Gloss with _$Gloss {
  const factory Gloss({
    @JsonKey(name: 'content_id') required String contentId,
    @JsonKey(name: 'content_kind') required ContentKind contentKind,
    @JsonKey(name: 'ui_locale') required String uiLocale,
    required String text,
    @JsonKey(name: 'audio_ref') String? audioRef,
    required Provenance provenance,
  }) = _Gloss;
  factory Gloss.fromJson(Map<String, dynamic> json) => _$GlossFromJson(json);
}
