-- GENERATED by ratel-tools/codegen_ddl.py from schema/ (P0-6). DO NOT EDIT BY HAND.
-- Stage-3 user/runtime schema (P0-2). Apply to a DISPOSABLE pgserver DB only;
-- the live Supabase project is never touched. Regenerate: python3 ratel-tools/codegen_ddl.py

CREATE TYPE cefr_level AS ENUM ('A1', 'A2', 'B1', 'B2', 'C1', 'C2');
CREATE TYPE fsrs_state AS ENUM ('new', 'learning', 'review', 'relearning');
CREATE TYPE grant_source AS ENUM ('daily_free', 'review_free', 'ad_reward', 'purchase', 'subscription', 'promo', 'refund_reversal');
CREATE TYPE ledger_entry_type AS ENUM ('grant', 'spend', 'refund');

CREATE TABLE "user" (
    user_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    pro_until timestamptz,
    fsrs_weights jsonb,
    ui_locale text,
    timezone text,
    daily_goal_xp integer,
    PRIMARY KEY (user_id)
);

CREATE TABLE "user_course" (
    user_course_id uuid NOT NULL,
    user_id uuid NOT NULL,
    target_locale text NOT NULL,
    ui_locale text,
    theta_per_skill jsonb,
    cefr_target cefr_level,
    xp_total integer,
    lessons_completed integer,
    streak_days integer,
    streak_last_active date,
    diamonds integer,
    streak_freezes integer,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (user_course_id),
    UNIQUE (user_id, target_locale),
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
);

CREATE TABLE "user_item_state" (
    user_item_state_id uuid NOT NULL,
    user_id uuid NOT NULL,
    item_id text NOT NULL,
    stability double precision,
    difficulty double precision,
    due timestamptz NOT NULL,
    last_review timestamptz,
    reps integer,
    lapses integer,
    scheduled_days integer,
    state fsrs_state NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (user_item_state_id),
    UNIQUE (user_id, item_id),
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
);

CREATE INDEX ON "user_item_state" (user_id, due);

CREATE TABLE "user_phoneme_state" (
    user_phoneme_state_id uuid NOT NULL,
    user_id uuid NOT NULL,
    phoneme_id text NOT NULL,
    locale text,
    mastery double precision,
    attempts integer,
    last_score double precision,
    due timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (user_phoneme_state_id),
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
);

CREATE TABLE "placement_session" (
    placement_session_id uuid NOT NULL,
    user_id uuid NOT NULL,
    target_locale text NOT NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    theta_estimate double precision,
    se_estimate double precision,
    items_administered integer,
    result_cefr cefr_level,
    responses jsonb,
    created_at timestamptz,
    PRIMARY KEY (placement_session_id),
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
);

CREATE TABLE "review_log" (
    review_log_id uuid NOT NULL,
    user_id uuid NOT NULL,
    item_id text NOT NULL,
    reviewed_at timestamptz NOT NULL,
    rating integer NOT NULL,
    state fsrs_state,
    elapsed_days integer,
    scheduled_days integer,
    stability_after double precision,
    difficulty_after double precision,
    duration_ms integer,
    PRIMARY KEY (review_log_id, reviewed_at),
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
) PARTITION BY RANGE (reviewed_at);

CREATE TABLE "review_log_2026_06" PARTITION OF "review_log" FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE TABLE "review_log_2026_07" PARTITION OF "review_log" FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE INDEX ON "review_log" (user_id, reviewed_at);

CREATE TABLE "credit_ledger" (
    credit_ledger_id uuid NOT NULL,
    user_id uuid NOT NULL,
    entry_type ledger_entry_type NOT NULL,
    amount integer NOT NULL,
    balance_after integer,
    grant_source grant_source,
    client_event_id uuid NOT NULL,
    related_ledger_id uuid,
    reason text,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (credit_ledger_id),
    UNIQUE (client_event_id),
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
);
