/// Gentle-energy economy (R-J* / R-L3). Pure + unit-tested; in-memory only
/// (learner state stays interfaces/stubs until Stage 3 — R-O1).
///
/// Principles: mistakes NEVER cost energy; the start gate blocks ONLY a normal
/// empty-tank lesson; reviews and the first daily lesson are always free;
/// exactly one energy is spent on a normal lesson commit; Pro is unlimited.
class EnergyConfig {
  const EnergyConfig({
    this.maxEnergy = 5,
    this.lessonCost = 1,
    this.interstitialEvery = 3,
    this.regenSeconds = 1500,
    this.lessonXp = 20,
  });

  final int maxEnergy;
  final int lessonCost;

  /// Free-tier interstitial cadence (every Nth completed lesson). 0 disables.
  final int interstitialEvery;

  /// Real-time seconds to regenerate one energy point (25 min — spec §8).
  final int regenSeconds;

  /// Base XP credited per completed lesson — feeds the daily-goal ring.
  final int lessonXp;
}

class EnergyState {
  const EnergyState({
    this.energy = 5,
    this.isPro = false,
    this.dailyFreeUsed = false,
    this.lessonsCompleted = 0,
    this.xpToday = 0,
    this.refillAtMs,
    this.config = const EnergyConfig(),
  });

  final int energy;
  final bool isPro;

  /// Whether the always-free first daily (normal) lesson has been used.
  final bool dailyFreeUsed;
  final int lessonsCompleted;

  /// REAL XP earned this session toward the daily goal (+config.lessonXp per
  /// completed lesson; reviews don't count). In-memory like the rest (durable
  /// reset is R-O1) — never a faked number.
  final int xpToday;

  /// Wall-clock epoch-ms when the NEXT energy point regenerates; null = full or
  /// not regenerating. The countdown is COMPUTED from this real timestamp, so
  /// the model never fakes a decrementing number (R-O1-honest).
  final int? refillAtMs;

  final EnergyConfig config;

  bool get isUnlimited => isPro;

  /// A lesson can START unless it is a NORMAL lesson on an empty tank.
  /// Pro, reviews, and the first daily lesson are always allowed.
  bool canStart({required bool isReview}) {
    if (isPro || isReview || !dailyFreeUsed) return true;
    return energy >= config.lessonCost;
  }

  /// Seconds (ceil) until the next +1, or 0 when full / not regenerating.
  int remainingRefillSeconds(int nowMs) {
    final at = refillAtMs;
    if (at == null) return 0;
    final ms = at - nowMs;
    return ms <= 0 ? 0 : ((ms + 999) ~/ 1000);
  }

  /// Apply any energy that has regenerated by [nowMs] (real wall-clock based,
  /// with catch-up if several intervals elapsed). PURE — inject the clock in
  /// tests. Returns `this` unchanged when nothing regenerated.
  EnergyState regenerated(int nowMs) {
    if (isPro || energy >= config.maxEnergy) {
      return refillAtMs == null ? this : copyWith(clearRefill: true);
    }
    final start = refillAtMs;
    if (start == null) {
      // below max but no clock running yet — start it
      return copyWith(refillAtMs: nowMs + config.regenSeconds * 1000);
    }
    var e = energy;
    var next = start;
    while (e < config.maxEnergy && nowMs >= next) {
      e += 1;
      next += config.regenSeconds * 1000;
    }
    if (e == energy) return this; // clock running, nothing due yet
    if (e >= config.maxEnergy) return copyWith(energy: e, clearRefill: true);
    return copyWith(energy: e, refillAtMs: next);
  }

  EnergyState copyWith({
    int? energy,
    bool? isPro,
    bool? dailyFreeUsed,
    int? lessonsCompleted,
    int? xpToday,
    int? refillAtMs,
    bool clearRefill = false,
    EnergyConfig? config,
  }) =>
      EnergyState(
        energy: energy ?? this.energy,
        isPro: isPro ?? this.isPro,
        dailyFreeUsed: dailyFreeUsed ?? this.dailyFreeUsed,
        lessonsCompleted: lessonsCompleted ?? this.lessonsCompleted,
        xpToday: xpToday ?? this.xpToday,
        refillAtMs: clearRefill ? null : (refillAtMs ?? this.refillAtMs),
        config: config ?? this.config,
      );
}

/// What happened when a completed lesson was committed.
class EnergyCommitOutcome {
  const EnergyCommitOutcome({
    required this.energySpent,
    required this.showInterstitial,
    required this.energy,
    required this.wasFree,
  });

  final int energySpent;
  final bool showInterstitial;
  final int energy;
  final bool wasFree;
}
